import { Product } from "./types/Product";

export const sampleProducts: Product[] = [
  {
    _id: "1",
    name: "Nike Slim shirt",
    slug: "nike-slim-shirt",
    image: "/images/p1.jpg",
    category: "Shirts",
    price: 120,
    countInStock: 10,
    brand: "Nike",
    rating: 4.5,
    numReviews: 10,
    description: "high quality shirt",
  },
  {
    _id: "2",
    name: "Adidas Fit shirt",
    slug: "adidas-fit-shirt",
    image: "/images/p2.jpg",
    category: "Shirts",
    price: 120,
    countInStock: 10,
    brand: "Adidas",
    rating: 4.5,
    numReviews: 10,
    description: "high quality shirt",
  },
  {
    _id: "3",
    name: "Lacoste Free Pants",
    slug: "lacoste-free-pants",
    image: "/images/p2.jpg",
    category: "Pants",
    price: 220,
    countInStock: 0,
    brand: "Lacoste",
    rating: 4.8,
    numReviews: 17,
    description: "high quality pants",
  },
  {
    _id: "4",
    name: "Lacoste Free Pants",
    slug: "lacoste-free-pants-2",
    image: "/images/p3.jpg",
    category: "Pants",
    price: 85,
    countInStock: 0,
    brand: "Lacoste",
    rating: 4.8,
    numReviews: 17,
    description: "high quality pants",
  },
  {
    _id: "5",
    name: "Nike Slim Pants",
    slug: "nike-slim-pants",
    image: "/images/p1.jpg",
    category: "Pants",
    price: 78,
    countInStock: 0,
    brand: "Nike",
    rating: 4.5,
    numReviews: 14,
    description: "high quality pants",
  },
];
